name: HQC-256
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-ciphertext: 14485
length-public-key: 7245
length-secret-key: 7285
length-shared-secret: 64
nistkat-sha256: 1ab129ea5073cb933ffe70d77379f96dd869a9f816eab1a4a5165287942f20a7
principal-submitters:
  - Carlos Aguilar Melchor
  - Nicolas Aragon
  - Slim Bettaieb
  - Loïc Bidoux
  - Olivier Blazy
  - Jurjen Bos
  - Jean-Christophe Deneuville
  - Arnaud Dion
  - Philippe Gaborit
  - Jérôme Lacan
  - Edoardo Persichetti
  - Jean-Marc Robert
  - Pascal Véron
  - Gilles Zémor
implementations:
    - name: clean
      version: hqc-submission_2023-04-30 via https://github.com/SWilson4/package-pqclean/tree/<TO BE FILLED IN>
