name: HQC-RMRS-256
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-ciphertext: 14469
length-public-key: 7245
length-secret-key: 7285
length-shared-secret: 64
nistkat-sha256: 1ab129ea5073cb933ffe70d77379f96dd869a9f816eab1a4a5165287942f20a7
principal-submitters:
  - Carlos Aguilar Melchor
  - Nicolas Aragon
  - Slim Bettaieb
  - Olivier Blazy
  - Jurjen Bos
  - Jean-Christophe Deneuville
  - Philippe Gaborit
  - Edoardo Persichetti
  - Jean-Marc Robert
  - Pascal Véron
  - Gilles Zémor
  - Loïc Bidoux
implementations:
    - name: clean
      version: hqc-submission_2020-10-01 via https://github.com/jschanck/package-pqclean/tree/29f79e72/hqc
    - name: avx2
      version: hqc-submission_2020-10-01 via https://github.com/jschanck/package-pqclean/tree/29f79e72/hqc
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
                - bmi1
                - pclmulqdq
