name: HQC-RMRS-192
type: kem
claimed-nist-level: 3
claimed-security: IND-CCA2
length-ciphertext: 9026
length-public-key: 4522
length-secret-key: 4562
length-shared-secret: 64
nistkat-sha256: 54480a20bb50b95e6352f014625adf512c964d62146cc6063bc5e98c3c02fc9f
principal-submitters:
  - Carlos Aguilar Melchor
  - Nicolas Aragon
  - Slim Bettaieb
  - Olivier Blazy
  - Jurjen Bos
  - Jean-Christophe Deneuville
  - Philippe Gaborit
  - Edoardo Persichetti
  - Jean-Marc Robert
  - Pascal Véron
  - Gilles Zémor
  - Loïc Bidoux
implementations:
    - name: clean
      version: hqc-submission_2020-10-01 via https://github.com/jschanck/package-pqclean/tree/29f79e72/hqc
    - name: avx2
      version: hqc-submission_2020-10-01 via https://github.com/jschanck/package-pqclean/tree/29f79e72/hqc
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
                - bmi1
                - pclmulqdq
