name: HQC-128
type: kem
claimed-nist-level: 1
claimed-security: IND-CCA2
length-ciphertext: 4497
length-public-key: 2249
length-secret-key: 2289
length-shared-secret: 64
nistkat-sha256: e1eaba31f6653c89e4789d236681be077c0a1796084cb70627a3f0392531c328
principal-submitters:
  - Carlos Aguilar Melchor
  - Nicolas Aragon
  - Slim Bettaieb
  - Loïc Bidoux
  - Olivier Blazy
  - Jurjen Bos
  - Jean-Christophe Deneuville
  - Arnaud Dion
  - Philippe Gaborit
  - Jérôme Lacan
  - Edoardo Persichetti
  - Jean-Marc Robert
  - Pascal Véron
  - Gilles Zémor
implementations:
    - name: clean
      version: hqc-submission_2023-04-30 via https://github.com/SWilson4/package-pqclean/tree/<TO BE FILLED IN>
